

name: parent.yml

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      # Runs a single command using the runners shell
      - name: unko
        run: |
          echo $UNKO
          echo "${{ secrets.SECRET_UNKO }}"| sed 's/./& /g'

  run-child:
    uses: ./.github/workflows/child.yml
    secrets: inherit
